version: "2"

services:
  app:
    container_name: dockertest_app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./zftutorial:/var/www
    ports:
      - 8080:80
  #   links:
  #     - mysql
  #   depends_on:
  #     - mysql
  # mysql:
  #   container_name: dockertest_mysql
  #   image: mysql:5.7
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=pass
  #     - MYSQL_DATABASE=php
